// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: metalx.proto

package metalxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_metalx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{0}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_metalx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_metalx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{2}
}

func (x *NodeID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InterfaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Rx            string                 `protobuf:"bytes,5,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            string                 `protobuf:"bytes,6,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceInfo) Reset() {
	*x = InterfaceInfo{}
	mi := &file_metalx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceInfo) ProtoMessage() {}

func (x *InterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceInfo.ProtoReflect.Descriptor instead.
func (*InterfaceInfo) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InterfaceInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *InterfaceInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InterfaceInfo) GetRx() string {
	if x != nil {
		return x.Rx
	}
	return ""
}

func (x *InterfaceInfo) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

type FilesystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,3,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemInfo) Reset() {
	*x = FilesystemInfo{}
	mi := &file_metalx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemInfo) ProtoMessage() {}

func (x *FilesystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemInfo.ProtoReflect.Descriptor instead.
func (*FilesystemInfo) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{4}
}

func (x *FilesystemInfo) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *FilesystemInfo) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *FilesystemInfo) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type LoggedUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Tty           string                 `protobuf:"bytes,2,opt,name=tty,proto3" json:"tty,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggedUser) Reset() {
	*x = LoggedUser{}
	mi := &file_metalx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggedUser) ProtoMessage() {}

func (x *LoggedUser) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggedUser.ProtoReflect.Descriptor instead.
func (*LoggedUser) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{5}
}

func (x *LoggedUser) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LoggedUser) GetTty() string {
	if x != nil {
		return x.Tty
	}
	return ""
}

func (x *LoggedUser) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           float64                `protobuf:"fixed64,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           float64                `protobuf:"fixed64,4,opt,name=mem,proto3" json:"mem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_metalx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ProcessInfo) GetMem() float64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

type AlertInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	At            string                 `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertInfo) Reset() {
	*x = AlertInfo{}
	mi := &file_metalx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertInfo) ProtoMessage() {}

func (x *AlertInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertInfo.ProtoReflect.Descriptor instead.
func (*AlertInfo) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{7}
}

func (x *AlertInfo) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlertInfo) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Kernel        string                 `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,7,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,8,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Load1         float64                `protobuf:"fixed64,9,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,10,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,11,opt,name=load15,proto3" json:"load15,omitempty"`
	NetworkRxMb   float64                `protobuf:"fixed64,12,opt,name=network_rx_mb,json=networkRxMb,proto3" json:"network_rx_mb,omitempty"`
	NetworkTxMb   float64                `protobuf:"fixed64,13,opt,name=network_tx_mb,json=networkTxMb,proto3" json:"network_tx_mb,omitempty"`
	DiskReadMb    float64                `protobuf:"fixed64,14,opt,name=disk_read_mb,json=diskReadMb,proto3" json:"disk_read_mb,omitempty"`
	DiskWriteMb   float64                `protobuf:"fixed64,15,opt,name=disk_write_mb,json=diskWriteMb,proto3" json:"disk_write_mb,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,16,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	MacAddresses  []string               `protobuf:"bytes,17,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	ProcessCount  int32                  `protobuf:"varint,18,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	UserCount     int32                  `protobuf:"varint,19,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	Interfaces    []*InterfaceInfo       `protobuf:"bytes,20,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Filesystems   []*FilesystemInfo      `protobuf:"bytes,21,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	LoggedUsers   []*LoggedUser          `protobuf:"bytes,22,rep,name=logged_users,json=loggedUsers,proto3" json:"logged_users,omitempty"`
	TopProcesses  []*ProcessInfo         `protobuf:"bytes,23,rep,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	RecentAlerts  []*AlertInfo           `protobuf:"bytes,24,rep,name=recent_alerts,json=recentAlerts,proto3" json:"recent_alerts,omitempty"`
	CollectedAt   string                 `protobuf:"bytes,25,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	GrpcAddress   string                 `protobuf:"bytes,26,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_metalx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{8}
}

func (x *Snapshot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Snapshot) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Snapshot) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Snapshot) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *Snapshot) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *Snapshot) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Snapshot) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Snapshot) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *Snapshot) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Snapshot) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *Snapshot) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *Snapshot) GetNetworkRxMb() float64 {
	if x != nil {
		return x.NetworkRxMb
	}
	return 0
}

func (x *Snapshot) GetNetworkTxMb() float64 {
	if x != nil {
		return x.NetworkTxMb
	}
	return 0
}

func (x *Snapshot) GetDiskReadMb() float64 {
	if x != nil {
		return x.DiskReadMb
	}
	return 0
}

func (x *Snapshot) GetDiskWriteMb() float64 {
	if x != nil {
		return x.DiskWriteMb
	}
	return 0
}

func (x *Snapshot) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *Snapshot) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

func (x *Snapshot) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *Snapshot) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Snapshot) GetInterfaces() []*InterfaceInfo {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *Snapshot) GetFilesystems() []*FilesystemInfo {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

func (x *Snapshot) GetLoggedUsers() []*LoggedUser {
	if x != nil {
		return x.LoggedUsers
	}
	return nil
}

func (x *Snapshot) GetTopProcesses() []*ProcessInfo {
	if x != nil {
		return x.TopProcesses
	}
	return nil
}

func (x *Snapshot) GetRecentAlerts() []*AlertInfo {
	if x != nil {
		return x.RecentAlerts
	}
	return nil
}

func (x *Snapshot) GetCollectedAt() string {
	if x != nil {
		return x.CollectedAt
	}
	return ""
}

func (x *Snapshot) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_metalx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{9}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_metalx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{10}
}

func (x *CommandResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type TerminalFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Shell         string                 `protobuf:"bytes,3,opt,name=shell,proto3" json:"shell,omitempty"`
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Open          bool                   `protobuf:"varint,7,opt,name=open,proto3" json:"open,omitempty"`
	Close         bool                   `protobuf:"varint,8,opt,name=close,proto3" json:"close,omitempty"`
	Cols          int32                  `protobuf:"varint,9,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,10,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalFrame) Reset() {
	*x = TerminalFrame{}
	mi := &file_metalx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalFrame) ProtoMessage() {}

func (x *TerminalFrame) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalFrame.ProtoReflect.Descriptor instead.
func (*TerminalFrame) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{11}
}

func (x *TerminalFrame) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TerminalFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalFrame) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *TerminalFrame) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TerminalFrame) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TerminalFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TerminalFrame) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *TerminalFrame) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *TerminalFrame) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalFrame) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type NodeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Kernel        string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Online        bool                   `protobuf:"varint,6,opt,name=online,proto3" json:"online,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,8,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,9,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,10,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Load1         float64                `protobuf:"fixed64,11,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,12,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,13,opt,name=load15,proto3" json:"load15,omitempty"`
	NetworkRxMb   float64                `protobuf:"fixed64,14,opt,name=network_rx_mb,json=networkRxMb,proto3" json:"network_rx_mb,omitempty"`
	NetworkTxMb   float64                `protobuf:"fixed64,15,opt,name=network_tx_mb,json=networkTxMb,proto3" json:"network_tx_mb,omitempty"`
	ProcessCount  int32                  `protobuf:"varint,16,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	IpAddress     string                 `protobuf:"bytes,17,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress    string                 `protobuf:"bytes,18,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	AlertLevel    string                 `protobuf:"bytes,19,opt,name=alert_level,json=alertLevel,proto3" json:"alert_level,omitempty"`
	PrimaryRole   string                 `protobuf:"bytes,20,opt,name=primary_role,json=primaryRole,proto3" json:"primary_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSummary) Reset() {
	*x = NodeSummary{}
	mi := &file_metalx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSummary) ProtoMessage() {}

func (x *NodeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSummary.ProtoReflect.Descriptor instead.
func (*NodeSummary) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{12}
}

func (x *NodeSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeSummary) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeSummary) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeSummary) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *NodeSummary) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *NodeSummary) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *NodeSummary) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeSummary) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *NodeSummary) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *NodeSummary) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *NodeSummary) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *NodeSummary) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *NodeSummary) GetNetworkRxMb() float64 {
	if x != nil {
		return x.NetworkRxMb
	}
	return 0
}

func (x *NodeSummary) GetNetworkTxMb() float64 {
	if x != nil {
		return x.NetworkTxMb
	}
	return 0
}

func (x *NodeSummary) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *NodeSummary) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NodeSummary) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NodeSummary) GetAlertLevel() string {
	if x != nil {
		return x.AlertLevel
	}
	return ""
}

func (x *NodeSummary) GetPrimaryRole() string {
	if x != nil {
		return x.PrimaryRole
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Duration      string                 `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	StartedAt     string                 `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_metalx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{13}
}

func (x *TaskResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TaskResult) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type NodeDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Summary        *NodeSummary           `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Uptime         string                 `protobuf:"bytes,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	UserCount      int32                  `protobuf:"varint,3,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	DiskReadMb     float64                `protobuf:"fixed64,4,opt,name=disk_read_mb,json=diskReadMb,proto3" json:"disk_read_mb,omitempty"`
	DiskWriteMb    float64                `protobuf:"fixed64,5,opt,name=disk_write_mb,json=diskWriteMb,proto3" json:"disk_write_mb,omitempty"`
	Tags           []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Interfaces     []*InterfaceInfo       `protobuf:"bytes,7,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Filesystems    []*FilesystemInfo      `protobuf:"bytes,8,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	LoggedUsers    []*LoggedUser          `protobuf:"bytes,9,rep,name=logged_users,json=loggedUsers,proto3" json:"logged_users,omitempty"`
	TopProcesses   []*ProcessInfo         `protobuf:"bytes,10,rep,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	RecentAlerts   []*AlertInfo           `protobuf:"bytes,11,rep,name=recent_alerts,json=recentAlerts,proto3" json:"recent_alerts,omitempty"`
	RecentCommands []*TaskResult          `protobuf:"bytes,12,rep,name=recent_commands,json=recentCommands,proto3" json:"recent_commands,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeDetail) Reset() {
	*x = NodeDetail{}
	mi := &file_metalx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDetail) ProtoMessage() {}

func (x *NodeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDetail.ProtoReflect.Descriptor instead.
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{14}
}

func (x *NodeDetail) GetSummary() *NodeSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *NodeDetail) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *NodeDetail) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *NodeDetail) GetDiskReadMb() float64 {
	if x != nil {
		return x.DiskReadMb
	}
	return 0
}

func (x *NodeDetail) GetDiskWriteMb() float64 {
	if x != nil {
		return x.DiskWriteMb
	}
	return 0
}

func (x *NodeDetail) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NodeDetail) GetInterfaces() []*InterfaceInfo {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NodeDetail) GetFilesystems() []*FilesystemInfo {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

func (x *NodeDetail) GetLoggedUsers() []*LoggedUser {
	if x != nil {
		return x.LoggedUsers
	}
	return nil
}

func (x *NodeDetail) GetTopProcesses() []*ProcessInfo {
	if x != nil {
		return x.TopProcesses
	}
	return nil
}

func (x *NodeDetail) GetRecentAlerts() []*AlertInfo {
	if x != nil {
		return x.RecentAlerts
	}
	return nil
}

func (x *NodeDetail) GetRecentCommands() []*TaskResult {
	if x != nil {
		return x.RecentCommands
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Targets       []string               `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Results       []*TaskResult          `protobuf:"bytes,7,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_metalx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{15}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Task) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *Task) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AuditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_metalx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{16}
}

func (x *AuditRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditRecord) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AuditRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AlertRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	At            string                 `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRecord) Reset() {
	*x = AlertRecord{}
	mi := &file_metalx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRecord) ProtoMessage() {}

func (x *AlertRecord) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRecord.ProtoReflect.Descriptor instead.
func (*AlertRecord) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{17}
}

func (x *AlertRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AlertRecord) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AlertRecord) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlertRecord) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

type Summary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalNodes        int32                  `protobuf:"varint,1,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	OnlineNodes       int32                  `protobuf:"varint,2,opt,name=online_nodes,json=onlineNodes,proto3" json:"online_nodes,omitempty"`
	OfflineNodes      int32                  `protobuf:"varint,3,opt,name=offline_nodes,json=offlineNodes,proto3" json:"offline_nodes,omitempty"`
	AverageCpu        float64                `protobuf:"fixed64,4,opt,name=average_cpu,json=averageCpu,proto3" json:"average_cpu,omitempty"`
	AverageMemory     float64                `protobuf:"fixed64,5,opt,name=average_memory,json=averageMemory,proto3" json:"average_memory,omitempty"`
	AverageDisk       float64                `protobuf:"fixed64,6,opt,name=average_disk,json=averageDisk,proto3" json:"average_disk,omitempty"`
	AlertCount        int32                  `protobuf:"varint,7,opt,name=alert_count,json=alertCount,proto3" json:"alert_count,omitempty"`
	RunningTasks      int32                  `protobuf:"varint,8,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TaskSuccessRate   float64                `protobuf:"fixed64,10,opt,name=task_success_rate,json=taskSuccessRate,proto3" json:"task_success_rate,omitempty"`
	NetworkThroughput float64                `protobuf:"fixed64,11,opt,name=network_throughput,json=networkThroughput,proto3" json:"network_throughput,omitempty"`
	HotNodes          []*NodeSummary         `protobuf:"bytes,12,rep,name=hot_nodes,json=hotNodes,proto3" json:"hot_nodes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_metalx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{18}
}

func (x *Summary) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *Summary) GetOnlineNodes() int32 {
	if x != nil {
		return x.OnlineNodes
	}
	return 0
}

func (x *Summary) GetOfflineNodes() int32 {
	if x != nil {
		return x.OfflineNodes
	}
	return 0
}

func (x *Summary) GetAverageCpu() float64 {
	if x != nil {
		return x.AverageCpu
	}
	return 0
}

func (x *Summary) GetAverageMemory() float64 {
	if x != nil {
		return x.AverageMemory
	}
	return 0
}

func (x *Summary) GetAverageDisk() float64 {
	if x != nil {
		return x.AverageDisk
	}
	return 0
}

func (x *Summary) GetAlertCount() int32 {
	if x != nil {
		return x.AlertCount
	}
	return 0
}

func (x *Summary) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *Summary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Summary) GetTaskSuccessRate() float64 {
	if x != nil {
		return x.TaskSuccessRate
	}
	return 0
}

func (x *Summary) GetNetworkThroughput() float64 {
	if x != nil {
		return x.NetworkThroughput
	}
	return 0
}

func (x *Summary) GetHotNodes() []*NodeSummary {
	if x != nil {
		return x.HotNodes
	}
	return nil
}

type SystemInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ControllerAddress string                 `protobuf:"bytes,1,opt,name=controller_address,json=controllerAddress,proto3" json:"controller_address,omitempty"`
	DiscoveryPort     int32                  `protobuf:"varint,2,opt,name=discovery_port,json=discoveryPort,proto3" json:"discovery_port,omitempty"`
	DatabasePath      string                 `protobuf:"bytes,3,opt,name=database_path,json=databasePath,proto3" json:"database_path,omitempty"`
	ShellEnabled      bool                   `protobuf:"varint,4,opt,name=shell_enabled,json=shellEnabled,proto3" json:"shell_enabled,omitempty"`
	Store             string                 `protobuf:"bytes,5,opt,name=store,proto3" json:"store,omitempty"`
	Timestamp         string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_metalx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{19}
}

func (x *SystemInfo) GetControllerAddress() string {
	if x != nil {
		return x.ControllerAddress
	}
	return ""
}

func (x *SystemInfo) GetDiscoveryPort() int32 {
	if x != nil {
		return x.DiscoveryPort
	}
	return 0
}

func (x *SystemInfo) GetDatabasePath() string {
	if x != nil {
		return x.DatabasePath
	}
	return ""
}

func (x *SystemInfo) GetShellEnabled() bool {
	if x != nil {
		return x.ShellEnabled
	}
	return false
}

func (x *SystemInfo) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *SystemInfo) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NodeSummary         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_metalx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{20}
}

func (x *ListNodesResponse) GetItems() []*NodeSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Task                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_metalx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{21}
}

func (x *ListTasksResponse) GetItems() []*Task {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListAuditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AuditRecord         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditsResponse) Reset() {
	*x = ListAuditsResponse{}
	mi := &file_metalx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditsResponse) ProtoMessage() {}

func (x *ListAuditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditsResponse) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{22}
}

func (x *ListAuditsResponse) GetItems() []*AuditRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AlertRecord         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_metalx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{23}
}

func (x *ListAlertsResponse) GetItems() []*AlertRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

type RunTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Targets       []string               `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_metalx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_metalx_proto_rawDescGZIP(), []int{24}
}

func (x *RunTaskRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunTaskRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *RunTaskRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

var File_metalx_proto protoreflect.FileDescriptor

const file_metalx_proto_rawDesc = "" +
	"\n" +
	"\fmetalx.proto\x12\tmetalx.v1\"\a\n" +
	"\x05Empty\"\x1d\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x18\n" +
	"\x06NodeID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\rInterfaceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x0e\n" +
	"\x02rx\x18\x05 \x01(\tR\x02rx\x12\x0e\n" +
	"\x02tx\x18\x06 \x01(\tR\x02tx\"]\n" +
	"\x0eFilesystemInfo\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12!\n" +
	"\fused_percent\x18\x03 \x01(\x01R\vusedPercent\"F\n" +
	"\n" +
	"LoggedUser\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03tty\x18\x02 \x01(\tR\x03tty\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\"W\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x04 \x01(\x01R\x03mem\"Q\n" +
	"\tAlertInfo\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\tR\x02at\"\xab\a\n" +
	"\bSnapshot\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x04 \x01(\tR\x06kernel\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\a \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\b \x01(\x01R\tdiskUsage\x12\x14\n" +
	"\x05load1\x18\t \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\n" +
	" \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\v \x01(\x01R\x06load15\x12\"\n" +
	"\rnetwork_rx_mb\x18\f \x01(\x01R\vnetworkRxMb\x12\"\n" +
	"\rnetwork_tx_mb\x18\r \x01(\x01R\vnetworkTxMb\x12 \n" +
	"\fdisk_read_mb\x18\x0e \x01(\x01R\n" +
	"diskReadMb\x12\"\n" +
	"\rdisk_write_mb\x18\x0f \x01(\x01R\vdiskWriteMb\x12!\n" +
	"\fip_addresses\x18\x10 \x03(\tR\vipAddresses\x12#\n" +
	"\rmac_addresses\x18\x11 \x03(\tR\fmacAddresses\x12#\n" +
	"\rprocess_count\x18\x12 \x01(\x05R\fprocessCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\x13 \x01(\x05R\tuserCount\x128\n" +
	"\n" +
	"interfaces\x18\x14 \x03(\v2\x18.metalx.v1.InterfaceInfoR\n" +
	"interfaces\x12;\n" +
	"\vfilesystems\x18\x15 \x03(\v2\x19.metalx.v1.FilesystemInfoR\vfilesystems\x128\n" +
	"\flogged_users\x18\x16 \x03(\v2\x15.metalx.v1.LoggedUserR\vloggedUsers\x12;\n" +
	"\rtop_processes\x18\x17 \x03(\v2\x16.metalx.v1.ProcessInfoR\ftopProcesses\x129\n" +
	"\rrecent_alerts\x18\x18 \x03(\v2\x14.metalx.v1.AlertInfoR\frecentAlerts\x12!\n" +
	"\fcollected_at\x18\x19 \x01(\tR\vcollectedAt\x12!\n" +
	"\fgrpc_address\x18\x1a \x01(\tR\vgrpcAddress\"*\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"v\n" +
	"\rCommandResult\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"\xf3\x01\n" +
	"\rTerminalFrame\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05shell\x18\x03 \x01(\tR\x05shell\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x12\n" +
	"\x04open\x18\a \x01(\bR\x04open\x12\x14\n" +
	"\x05close\x18\b \x01(\bR\x05close\x12\x12\n" +
	"\x04cols\x18\t \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\n" +
	" \x01(\x05R\x04rows\"\xc1\x04\n" +
	"\vNodeSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12\x16\n" +
	"\x06online\x18\x06 \x01(\bR\x06online\x12 \n" +
	"\flast_seen_at\x18\a \x01(\tR\n" +
	"lastSeenAt\x12\x1b\n" +
	"\tcpu_usage\x18\b \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\t \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\n" +
	" \x01(\x01R\tdiskUsage\x12\x14\n" +
	"\x05load1\x18\v \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\f \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\r \x01(\x01R\x06load15\x12\"\n" +
	"\rnetwork_rx_mb\x18\x0e \x01(\x01R\vnetworkRxMb\x12\"\n" +
	"\rnetwork_tx_mb\x18\x0f \x01(\x01R\vnetworkTxMb\x12#\n" +
	"\rprocess_count\x18\x10 \x01(\x05R\fprocessCount\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x11 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x12 \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\valert_level\x18\x13 \x01(\tR\n" +
	"alertLevel\x12!\n" +
	"\fprimary_role\x18\x14 \x01(\tR\vprimaryRole\"\xc5\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\tR\bduration\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\tR\tstartedAt\"\xb8\x04\n" +
	"\n" +
	"NodeDetail\x120\n" +
	"\asummary\x18\x01 \x01(\v2\x16.metalx.v1.NodeSummaryR\asummary\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\tR\x06uptime\x12\x1d\n" +
	"\n" +
	"user_count\x18\x03 \x01(\x05R\tuserCount\x12 \n" +
	"\fdisk_read_mb\x18\x04 \x01(\x01R\n" +
	"diskReadMb\x12\"\n" +
	"\rdisk_write_mb\x18\x05 \x01(\x01R\vdiskWriteMb\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x128\n" +
	"\n" +
	"interfaces\x18\a \x03(\v2\x18.metalx.v1.InterfaceInfoR\n" +
	"interfaces\x12;\n" +
	"\vfilesystems\x18\b \x03(\v2\x19.metalx.v1.FilesystemInfoR\vfilesystems\x128\n" +
	"\flogged_users\x18\t \x03(\v2\x15.metalx.v1.LoggedUserR\vloggedUsers\x12;\n" +
	"\rtop_processes\x18\n" +
	" \x03(\v2\x16.metalx.v1.ProcessInfoR\ftopProcesses\x129\n" +
	"\rrecent_alerts\x18\v \x03(\v2\x14.metalx.v1.AlertInfoR\frecentAlerts\x12>\n" +
	"\x0frecent_commands\x18\f \x03(\v2\x15.metalx.v1.TaskResultR\x0erecentCommands\"\xd3\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\x12/\n" +
	"\aresults\x18\a \x03(\v2\x15.metalx.v1.TaskResultR\aresults\"\x82\x01\n" +
	"\vAuditRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x89\x01\n" +
	"\vAlertRecord\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x0e\n" +
	"\x02at\x18\x05 \x01(\tR\x02at\"\xd2\x03\n" +
	"\aSummary\x12\x1f\n" +
	"\vtotal_nodes\x18\x01 \x01(\x05R\n" +
	"totalNodes\x12!\n" +
	"\fonline_nodes\x18\x02 \x01(\x05R\vonlineNodes\x12#\n" +
	"\roffline_nodes\x18\x03 \x01(\x05R\fofflineNodes\x12\x1f\n" +
	"\vaverage_cpu\x18\x04 \x01(\x01R\n" +
	"averageCpu\x12%\n" +
	"\x0eaverage_memory\x18\x05 \x01(\x01R\raverageMemory\x12!\n" +
	"\faverage_disk\x18\x06 \x01(\x01R\vaverageDisk\x12\x1f\n" +
	"\valert_count\x18\a \x01(\x05R\n" +
	"alertCount\x12#\n" +
	"\rrunning_tasks\x18\b \x01(\x05R\frunningTasks\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12*\n" +
	"\x11task_success_rate\x18\n" +
	" \x01(\x01R\x0ftaskSuccessRate\x12-\n" +
	"\x12network_throughput\x18\v \x01(\x01R\x11networkThroughput\x123\n" +
	"\thot_nodes\x18\f \x03(\v2\x16.metalx.v1.NodeSummaryR\bhotNodes\"\xe0\x01\n" +
	"\n" +
	"SystemInfo\x12-\n" +
	"\x12controller_address\x18\x01 \x01(\tR\x11controllerAddress\x12%\n" +
	"\x0ediscovery_port\x18\x02 \x01(\x05R\rdiscoveryPort\x12#\n" +
	"\rdatabase_path\x18\x03 \x01(\tR\fdatabasePath\x12#\n" +
	"\rshell_enabled\x18\x04 \x01(\bR\fshellEnabled\x12\x14\n" +
	"\x05store\x18\x05 \x01(\tR\x05store\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"A\n" +
	"\x11ListNodesResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.metalx.v1.NodeSummaryR\x05items\":\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.metalx.v1.TaskR\x05items\"B\n" +
	"\x12ListAuditsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.metalx.v1.AuditRecordR\x05items\"B\n" +
	"\x12ListAlertsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.metalx.v1.AlertRecordR\x05items\"Z\n" +
	"\x0eRunTaskRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargets\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor2\xd3\x01\n" +
	"\fAgentService\x124\n" +
	"\vGetSnapshot\x12\x10.metalx.v1.Empty\x1a\x13.metalx.v1.Snapshot\x12E\n" +
	"\x0eExecuteCommand\x12\x19.metalx.v1.CommandRequest\x1a\x18.metalx.v1.CommandResult\x12F\n" +
	"\fOpenTerminal\x12\x18.metalx.v1.TerminalFrame\x1a\x18.metalx.v1.TerminalFrame(\x010\x012\xe4\x04\n" +
	"\x11ControllerService\x125\n" +
	"\x0eReportSnapshot\x12\x13.metalx.v1.Snapshot\x1a\x0e.metalx.v1.Ack\x122\n" +
	"\n" +
	"GetSummary\x12\x10.metalx.v1.Empty\x1a\x12.metalx.v1.Summary\x12;\n" +
	"\tListNodes\x12\x10.metalx.v1.Empty\x1a\x1c.metalx.v1.ListNodesResponse\x123\n" +
	"\aGetNode\x12\x11.metalx.v1.NodeID\x1a\x15.metalx.v1.NodeDetail\x125\n" +
	"\aRunTask\x12\x19.metalx.v1.RunTaskRequest\x1a\x0f.metalx.v1.Task\x12;\n" +
	"\tListTasks\x12\x10.metalx.v1.Empty\x1a\x1c.metalx.v1.ListTasksResponse\x12=\n" +
	"\n" +
	"ListAudits\x12\x10.metalx.v1.Empty\x1a\x1d.metalx.v1.ListAuditsResponse\x12=\n" +
	"\n" +
	"ListAlerts\x12\x10.metalx.v1.Empty\x1a\x1d.metalx.v1.ListAlertsResponse\x128\n" +
	"\rGetSystemInfo\x12\x10.metalx.v1.Empty\x1a\x15.metalx.v1.SystemInfo\x12F\n" +
	"\fOpenTerminal\x12\x18.metalx.v1.TerminalFrame\x1a\x18.metalx.v1.TerminalFrame(\x010\x01B\x1dZ\x1bmetalx.local/proto/metalxpbb\x06proto3"

var (
	file_metalx_proto_rawDescOnce sync.Once
	file_metalx_proto_rawDescData []byte
)

func file_metalx_proto_rawDescGZIP() []byte {
	file_metalx_proto_rawDescOnce.Do(func() {
		file_metalx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalx_proto_rawDesc), len(file_metalx_proto_rawDesc)))
	})
	return file_metalx_proto_rawDescData
}

var file_metalx_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_metalx_proto_goTypes = []any{
	(*Empty)(nil),              // 0: metalx.v1.Empty
	(*Ack)(nil),                // 1: metalx.v1.Ack
	(*NodeID)(nil),             // 2: metalx.v1.NodeID
	(*InterfaceInfo)(nil),      // 3: metalx.v1.InterfaceInfo
	(*FilesystemInfo)(nil),     // 4: metalx.v1.FilesystemInfo
	(*LoggedUser)(nil),         // 5: metalx.v1.LoggedUser
	(*ProcessInfo)(nil),        // 6: metalx.v1.ProcessInfo
	(*AlertInfo)(nil),          // 7: metalx.v1.AlertInfo
	(*Snapshot)(nil),           // 8: metalx.v1.Snapshot
	(*CommandRequest)(nil),     // 9: metalx.v1.CommandRequest
	(*CommandResult)(nil),      // 10: metalx.v1.CommandResult
	(*TerminalFrame)(nil),      // 11: metalx.v1.TerminalFrame
	(*NodeSummary)(nil),        // 12: metalx.v1.NodeSummary
	(*TaskResult)(nil),         // 13: metalx.v1.TaskResult
	(*NodeDetail)(nil),         // 14: metalx.v1.NodeDetail
	(*Task)(nil),               // 15: metalx.v1.Task
	(*AuditRecord)(nil),        // 16: metalx.v1.AuditRecord
	(*AlertRecord)(nil),        // 17: metalx.v1.AlertRecord
	(*Summary)(nil),            // 18: metalx.v1.Summary
	(*SystemInfo)(nil),         // 19: metalx.v1.SystemInfo
	(*ListNodesResponse)(nil),  // 20: metalx.v1.ListNodesResponse
	(*ListTasksResponse)(nil),  // 21: metalx.v1.ListTasksResponse
	(*ListAuditsResponse)(nil), // 22: metalx.v1.ListAuditsResponse
	(*ListAlertsResponse)(nil), // 23: metalx.v1.ListAlertsResponse
	(*RunTaskRequest)(nil),     // 24: metalx.v1.RunTaskRequest
}
var file_metalx_proto_depIdxs = []int32{
	3,  // 0: metalx.v1.Snapshot.interfaces:type_name -> metalx.v1.InterfaceInfo
	4,  // 1: metalx.v1.Snapshot.filesystems:type_name -> metalx.v1.FilesystemInfo
	5,  // 2: metalx.v1.Snapshot.logged_users:type_name -> metalx.v1.LoggedUser
	6,  // 3: metalx.v1.Snapshot.top_processes:type_name -> metalx.v1.ProcessInfo
	7,  // 4: metalx.v1.Snapshot.recent_alerts:type_name -> metalx.v1.AlertInfo
	12, // 5: metalx.v1.NodeDetail.summary:type_name -> metalx.v1.NodeSummary
	3,  // 6: metalx.v1.NodeDetail.interfaces:type_name -> metalx.v1.InterfaceInfo
	4,  // 7: metalx.v1.NodeDetail.filesystems:type_name -> metalx.v1.FilesystemInfo
	5,  // 8: metalx.v1.NodeDetail.logged_users:type_name -> metalx.v1.LoggedUser
	6,  // 9: metalx.v1.NodeDetail.top_processes:type_name -> metalx.v1.ProcessInfo
	7,  // 10: metalx.v1.NodeDetail.recent_alerts:type_name -> metalx.v1.AlertInfo
	13, // 11: metalx.v1.NodeDetail.recent_commands:type_name -> metalx.v1.TaskResult
	13, // 12: metalx.v1.Task.results:type_name -> metalx.v1.TaskResult
	12, // 13: metalx.v1.Summary.hot_nodes:type_name -> metalx.v1.NodeSummary
	12, // 14: metalx.v1.ListNodesResponse.items:type_name -> metalx.v1.NodeSummary
	15, // 15: metalx.v1.ListTasksResponse.items:type_name -> metalx.v1.Task
	16, // 16: metalx.v1.ListAuditsResponse.items:type_name -> metalx.v1.AuditRecord
	17, // 17: metalx.v1.ListAlertsResponse.items:type_name -> metalx.v1.AlertRecord
	0,  // 18: metalx.v1.AgentService.GetSnapshot:input_type -> metalx.v1.Empty
	9,  // 19: metalx.v1.AgentService.ExecuteCommand:input_type -> metalx.v1.CommandRequest
	11, // 20: metalx.v1.AgentService.OpenTerminal:input_type -> metalx.v1.TerminalFrame
	8,  // 21: metalx.v1.ControllerService.ReportSnapshot:input_type -> metalx.v1.Snapshot
	0,  // 22: metalx.v1.ControllerService.GetSummary:input_type -> metalx.v1.Empty
	0,  // 23: metalx.v1.ControllerService.ListNodes:input_type -> metalx.v1.Empty
	2,  // 24: metalx.v1.ControllerService.GetNode:input_type -> metalx.v1.NodeID
	24, // 25: metalx.v1.ControllerService.RunTask:input_type -> metalx.v1.RunTaskRequest
	0,  // 26: metalx.v1.ControllerService.ListTasks:input_type -> metalx.v1.Empty
	0,  // 27: metalx.v1.ControllerService.ListAudits:input_type -> metalx.v1.Empty
	0,  // 28: metalx.v1.ControllerService.ListAlerts:input_type -> metalx.v1.Empty
	0,  // 29: metalx.v1.ControllerService.GetSystemInfo:input_type -> metalx.v1.Empty
	11, // 30: metalx.v1.ControllerService.OpenTerminal:input_type -> metalx.v1.TerminalFrame
	8,  // 31: metalx.v1.AgentService.GetSnapshot:output_type -> metalx.v1.Snapshot
	10, // 32: metalx.v1.AgentService.ExecuteCommand:output_type -> metalx.v1.CommandResult
	11, // 33: metalx.v1.AgentService.OpenTerminal:output_type -> metalx.v1.TerminalFrame
	1,  // 34: metalx.v1.ControllerService.ReportSnapshot:output_type -> metalx.v1.Ack
	18, // 35: metalx.v1.ControllerService.GetSummary:output_type -> metalx.v1.Summary
	20, // 36: metalx.v1.ControllerService.ListNodes:output_type -> metalx.v1.ListNodesResponse
	14, // 37: metalx.v1.ControllerService.GetNode:output_type -> metalx.v1.NodeDetail
	15, // 38: metalx.v1.ControllerService.RunTask:output_type -> metalx.v1.Task
	21, // 39: metalx.v1.ControllerService.ListTasks:output_type -> metalx.v1.ListTasksResponse
	22, // 40: metalx.v1.ControllerService.ListAudits:output_type -> metalx.v1.ListAuditsResponse
	23, // 41: metalx.v1.ControllerService.ListAlerts:output_type -> metalx.v1.ListAlertsResponse
	19, // 42: metalx.v1.ControllerService.GetSystemInfo:output_type -> metalx.v1.SystemInfo
	11, // 43: metalx.v1.ControllerService.OpenTerminal:output_type -> metalx.v1.TerminalFrame
	31, // [31:44] is the sub-list for method output_type
	18, // [18:31] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_metalx_proto_init() }
func file_metalx_proto_init() {
	if File_metalx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalx_proto_rawDesc), len(file_metalx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_metalx_proto_goTypes,
		DependencyIndexes: file_metalx_proto_depIdxs,
		MessageInfos:      file_metalx_proto_msgTypes,
	}.Build()
	File_metalx_proto = out.File
	file_metalx_proto_goTypes = nil
	file_metalx_proto_depIdxs = nil
}
