// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: metalx.proto

package metalxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_GetSnapshot_FullMethodName    = "/metalx.v1.AgentService/GetSnapshot"
	AgentService_ExecuteCommand_FullMethodName = "/metalx.v1.AgentService/ExecuteCommand"
	AgentService_OpenTerminal_FullMethodName   = "/metalx.v1.AgentService/OpenTerminal"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	GetSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Snapshot, error)
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResult, error)
	OpenTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, AgentService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, AgentService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) OpenTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_OpenTerminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalFrame, TerminalFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_OpenTerminalClient = grpc.BidiStreamingClient[TerminalFrame, TerminalFrame]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	GetSnapshot(context.Context, *Empty) (*Snapshot, error)
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResult, error)
	OpenTerminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GetSnapshot(context.Context, *Empty) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedAgentServiceServer) OpenTerminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error {
	return status.Errorf(codes.Unimplemented, "method OpenTerminal not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSnapshot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_OpenTerminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).OpenTerminal(&grpc.GenericServerStream[TerminalFrame, TerminalFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_OpenTerminalServer = grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metalx.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _AgentService_GetSnapshot_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _AgentService_ExecuteCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenTerminal",
			Handler:       _AgentService_OpenTerminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "metalx.proto",
}

const (
	ControllerService_ReportSnapshot_FullMethodName        = "/metalx.v1.ControllerService/ReportSnapshot"
	ControllerService_GetSummary_FullMethodName            = "/metalx.v1.ControllerService/GetSummary"
	ControllerService_ListNodes_FullMethodName             = "/metalx.v1.ControllerService/ListNodes"
	ControllerService_GetNode_FullMethodName               = "/metalx.v1.ControllerService/GetNode"
	ControllerService_RunTask_FullMethodName               = "/metalx.v1.ControllerService/RunTask"
	ControllerService_ListTasks_FullMethodName             = "/metalx.v1.ControllerService/ListTasks"
	ControllerService_ListAudits_FullMethodName            = "/metalx.v1.ControllerService/ListAudits"
	ControllerService_ListAlerts_FullMethodName            = "/metalx.v1.ControllerService/ListAlerts"
	ControllerService_GetSystemInfo_FullMethodName         = "/metalx.v1.ControllerService/GetSystemInfo"
	ControllerService_GetDnsmasqSettings_FullMethodName    = "/metalx.v1.ControllerService/GetDnsmasqSettings"
	ControllerService_UpdateDnsmasqSettings_FullMethodName = "/metalx.v1.ControllerService/UpdateDnsmasqSettings"
	ControllerService_ListInstallProfiles_FullMethodName   = "/metalx.v1.ControllerService/ListInstallProfiles"
	ControllerService_UpsertInstallProfile_FullMethodName  = "/metalx.v1.ControllerService/UpsertInstallProfile"
	ControllerService_ListInstallJobs_FullMethodName       = "/metalx.v1.ControllerService/ListInstallJobs"
	ControllerService_CreateInstallJob_FullMethodName      = "/metalx.v1.ControllerService/CreateInstallJob"
	ControllerService_GetInstallJob_FullMethodName         = "/metalx.v1.ControllerService/GetInstallJob"
	ControllerService_GetAppSettings_FullMethodName        = "/metalx.v1.ControllerService/GetAppSettings"
	ControllerService_UpdateAppSettings_FullMethodName     = "/metalx.v1.ControllerService/UpdateAppSettings"
	ControllerService_OpenTerminal_FullMethodName          = "/metalx.v1.ControllerService/OpenTerminal"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	ReportSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*Ack, error)
	GetSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Summary, error)
	ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListNodesResponse, error)
	GetNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeDetail, error)
	RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTasksResponse, error)
	ListAudits(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAuditsResponse, error)
	ListAlerts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	GetSystemInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemInfo, error)
	GetDnsmasqSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DnsmasqSettings, error)
	UpdateDnsmasqSettings(ctx context.Context, in *UpdateDnsmasqSettingsRequest, opts ...grpc.CallOption) (*DnsmasqSettings, error)
	ListInstallProfiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListInstallProfilesResponse, error)
	UpsertInstallProfile(ctx context.Context, in *UpsertInstallProfileRequest, opts ...grpc.CallOption) (*InstallProfile, error)
	ListInstallJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListInstallJobsResponse, error)
	CreateInstallJob(ctx context.Context, in *CreateInstallJobRequest, opts ...grpc.CallOption) (*InstallJob, error)
	GetInstallJob(ctx context.Context, in *InstallJobID, opts ...grpc.CallOption) (*InstallJob, error)
	GetAppSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppSettings, error)
	UpdateAppSettings(ctx context.Context, in *UpdateAppSettingsRequest, opts ...grpc.CallOption) (*AppSettings, error)
	OpenTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) ReportSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControllerService_ReportSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Summary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Summary)
	err := c.cc.Invoke(ctx, ControllerService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, ControllerService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeDetail)
	err := c.cc.Invoke(ctx, ControllerService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, ControllerService_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ListTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, ControllerService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ListAudits(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAuditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditsResponse)
	err := c.cc.Invoke(ctx, ControllerService_ListAudits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ListAlerts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, ControllerService_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetSystemInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemInfo)
	err := c.cc.Invoke(ctx, ControllerService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetDnsmasqSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DnsmasqSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsmasqSettings)
	err := c.cc.Invoke(ctx, ControllerService_GetDnsmasqSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) UpdateDnsmasqSettings(ctx context.Context, in *UpdateDnsmasqSettingsRequest, opts ...grpc.CallOption) (*DnsmasqSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsmasqSettings)
	err := c.cc.Invoke(ctx, ControllerService_UpdateDnsmasqSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ListInstallProfiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListInstallProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstallProfilesResponse)
	err := c.cc.Invoke(ctx, ControllerService_ListInstallProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) UpsertInstallProfile(ctx context.Context, in *UpsertInstallProfileRequest, opts ...grpc.CallOption) (*InstallProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallProfile)
	err := c.cc.Invoke(ctx, ControllerService_UpsertInstallProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ListInstallJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListInstallJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstallJobsResponse)
	err := c.cc.Invoke(ctx, ControllerService_ListInstallJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) CreateInstallJob(ctx context.Context, in *CreateInstallJobRequest, opts ...grpc.CallOption) (*InstallJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallJob)
	err := c.cc.Invoke(ctx, ControllerService_CreateInstallJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetInstallJob(ctx context.Context, in *InstallJobID, opts ...grpc.CallOption) (*InstallJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallJob)
	err := c.cc.Invoke(ctx, ControllerService_GetInstallJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetAppSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AppSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppSettings)
	err := c.cc.Invoke(ctx, ControllerService_GetAppSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) UpdateAppSettings(ctx context.Context, in *UpdateAppSettingsRequest, opts ...grpc.CallOption) (*AppSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppSettings)
	err := c.cc.Invoke(ctx, ControllerService_UpdateAppSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) OpenTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControllerService_ServiceDesc.Streams[0], ControllerService_OpenTerminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalFrame, TerminalFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerService_OpenTerminalClient = grpc.BidiStreamingClient[TerminalFrame, TerminalFrame]

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
type ControllerServiceServer interface {
	ReportSnapshot(context.Context, *Snapshot) (*Ack, error)
	GetSummary(context.Context, *Empty) (*Summary, error)
	ListNodes(context.Context, *Empty) (*ListNodesResponse, error)
	GetNode(context.Context, *NodeID) (*NodeDetail, error)
	RunTask(context.Context, *RunTaskRequest) (*Task, error)
	ListTasks(context.Context, *Empty) (*ListTasksResponse, error)
	ListAudits(context.Context, *Empty) (*ListAuditsResponse, error)
	ListAlerts(context.Context, *Empty) (*ListAlertsResponse, error)
	GetSystemInfo(context.Context, *Empty) (*SystemInfo, error)
	GetDnsmasqSettings(context.Context, *Empty) (*DnsmasqSettings, error)
	UpdateDnsmasqSettings(context.Context, *UpdateDnsmasqSettingsRequest) (*DnsmasqSettings, error)
	ListInstallProfiles(context.Context, *Empty) (*ListInstallProfilesResponse, error)
	UpsertInstallProfile(context.Context, *UpsertInstallProfileRequest) (*InstallProfile, error)
	ListInstallJobs(context.Context, *Empty) (*ListInstallJobsResponse, error)
	CreateInstallJob(context.Context, *CreateInstallJobRequest) (*InstallJob, error)
	GetInstallJob(context.Context, *InstallJobID) (*InstallJob, error)
	GetAppSettings(context.Context, *Empty) (*AppSettings, error)
	UpdateAppSettings(context.Context, *UpdateAppSettingsRequest) (*AppSettings, error)
	OpenTerminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) ReportSnapshot(context.Context, *Snapshot) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSnapshot not implemented")
}
func (UnimplementedControllerServiceServer) GetSummary(context.Context, *Empty) (*Summary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedControllerServiceServer) ListNodes(context.Context, *Empty) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedControllerServiceServer) GetNode(context.Context, *NodeID) (*NodeDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedControllerServiceServer) RunTask(context.Context, *RunTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedControllerServiceServer) ListTasks(context.Context, *Empty) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedControllerServiceServer) ListAudits(context.Context, *Empty) (*ListAuditsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAudits not implemented")
}
func (UnimplementedControllerServiceServer) ListAlerts(context.Context, *Empty) (*ListAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedControllerServiceServer) GetSystemInfo(context.Context, *Empty) (*SystemInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedControllerServiceServer) GetDnsmasqSettings(context.Context, *Empty) (*DnsmasqSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDnsmasqSettings not implemented")
}
func (UnimplementedControllerServiceServer) UpdateDnsmasqSettings(context.Context, *UpdateDnsmasqSettingsRequest) (*DnsmasqSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDnsmasqSettings not implemented")
}
func (UnimplementedControllerServiceServer) ListInstallProfiles(context.Context, *Empty) (*ListInstallProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstallProfiles not implemented")
}
func (UnimplementedControllerServiceServer) UpsertInstallProfile(context.Context, *UpsertInstallProfileRequest) (*InstallProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertInstallProfile not implemented")
}
func (UnimplementedControllerServiceServer) ListInstallJobs(context.Context, *Empty) (*ListInstallJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstallJobs not implemented")
}
func (UnimplementedControllerServiceServer) CreateInstallJob(context.Context, *CreateInstallJobRequest) (*InstallJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstallJob not implemented")
}
func (UnimplementedControllerServiceServer) GetInstallJob(context.Context, *InstallJobID) (*InstallJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstallJob not implemented")
}
func (UnimplementedControllerServiceServer) GetAppSettings(context.Context, *Empty) (*AppSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppSettings not implemented")
}
func (UnimplementedControllerServiceServer) UpdateAppSettings(context.Context, *UpdateAppSettingsRequest) (*AppSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAppSettings not implemented")
}
func (UnimplementedControllerServiceServer) OpenTerminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error {
	return status.Errorf(codes.Unimplemented, "method OpenTerminal not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call pancis, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_ReportSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReportSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ReportSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReportSnapshot(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetSummary(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ListNodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetNode(ctx, req.(*NodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).RunTask(ctx, req.(*RunTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ListTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ListAudits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ListAudits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ListAudits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ListAudits(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ListAlerts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetSystemInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetDnsmasqSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetDnsmasqSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetDnsmasqSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetDnsmasqSettings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_UpdateDnsmasqSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDnsmasqSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).UpdateDnsmasqSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_UpdateDnsmasqSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).UpdateDnsmasqSettings(ctx, req.(*UpdateDnsmasqSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ListInstallProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ListInstallProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ListInstallProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ListInstallProfiles(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_UpsertInstallProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertInstallProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).UpsertInstallProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_UpsertInstallProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).UpsertInstallProfile(ctx, req.(*UpsertInstallProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ListInstallJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ListInstallJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ListInstallJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ListInstallJobs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_CreateInstallJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstallJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).CreateInstallJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_CreateInstallJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).CreateInstallJob(ctx, req.(*CreateInstallJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetInstallJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallJobID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetInstallJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetInstallJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetInstallJob(ctx, req.(*InstallJobID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetAppSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetAppSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetAppSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetAppSettings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_UpdateAppSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).UpdateAppSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_UpdateAppSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).UpdateAppSettings(ctx, req.(*UpdateAppSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_OpenTerminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServiceServer).OpenTerminal(&grpc.GenericServerStream[TerminalFrame, TerminalFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerService_OpenTerminalServer = grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metalx.v1.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportSnapshot",
			Handler:    _ControllerService_ReportSnapshot_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _ControllerService_GetSummary_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _ControllerService_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _ControllerService_GetNode_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _ControllerService_RunTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ControllerService_ListTasks_Handler,
		},
		{
			MethodName: "ListAudits",
			Handler:    _ControllerService_ListAudits_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _ControllerService_ListAlerts_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _ControllerService_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetDnsmasqSettings",
			Handler:    _ControllerService_GetDnsmasqSettings_Handler,
		},
		{
			MethodName: "UpdateDnsmasqSettings",
			Handler:    _ControllerService_UpdateDnsmasqSettings_Handler,
		},
		{
			MethodName: "ListInstallProfiles",
			Handler:    _ControllerService_ListInstallProfiles_Handler,
		},
		{
			MethodName: "UpsertInstallProfile",
			Handler:    _ControllerService_UpsertInstallProfile_Handler,
		},
		{
			MethodName: "ListInstallJobs",
			Handler:    _ControllerService_ListInstallJobs_Handler,
		},
		{
			MethodName: "CreateInstallJob",
			Handler:    _ControllerService_CreateInstallJob_Handler,
		},
		{
			MethodName: "GetInstallJob",
			Handler:    _ControllerService_GetInstallJob_Handler,
		},
		{
			MethodName: "GetAppSettings",
			Handler:    _ControllerService_GetAppSettings_Handler,
		},
		{
			MethodName: "UpdateAppSettings",
			Handler:    _ControllerService_UpdateAppSettings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenTerminal",
			Handler:       _ControllerService_OpenTerminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "metalx.proto",
}
